### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pianointhedark** [aturingmachine/laravel-vue-spa-boilerplate#3]
app.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at app.js:1
(anonymous) @ app.js:1

**Comment by aturingmachine** [comment]
Is this from a fresh install?

EDIT: I am having trouble recreating this issue. Can you give me some more info or let me know if you have solved the problem?

**Comment by aturingmachine** [comment]
I'm closing this because I cannot recreate and there is no context information provided.
